language: csharp
dist: trusty

sudo: false  # use the new container-based Travis infrastructure 

mono:
  - 5.0.1

os:
  - linux
  - osx

before_install:
  - chmod +x build.sh
 
script: 
  - ./build.sh All
